name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  commit-hooks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.12'
      - name: Install uv
        run: python -m pip install uv
      - uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-py3.12-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-py3.12-
      - name: Install dependencies
        run: uv sync --python 3.12 --frozen --all-groups --no-python-downloads
      - name: Run pre-commit hooks
        run: uv run --frozen --no-sync pre-commit run --all-files --show-diff-on-failure
