name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commit-hooks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install pre-commit and mypy
        run: pip install pre-commit && make dev
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
