name: Publish

on:
  push:
    branches:
      - main
  schedule:
    # Schedule: 5:30PM Monday-Friday UTC, which is roughly
    # 10:30 AM Pacific (give or take some DST) on weekdays.
    - cron: '30 17 * * MON-FRI'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04  # don't use "-latest", we can manually update
    env:
      GNUPGHOME: /tmp  # avoid "gpg: Fatal: can't create directory '/home/runner/.gnupg': File exists"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.12'
      - name: Install uv
        run: python -m pip install uv
      - uses: actions/cache@v6
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-py3.12-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-py3.12-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gzip bzip2 xz-utils zstd tar rpm cpio dpkg make
          uv sync --python 3.12 --frozen --no-dev --no-python-downloads
      - name: Checkout gh-pages and setup git
        run: |
          git fetch origin gh-pages --depth=1
          git worktree add ../gh-pages gh-pages
          git config --global user.name 'Github Actions'
          git config --global user.email 'noreply@example.com'
      - name: Fetch updates and build page
        run: |
          uv run --frozen --no-dev --no-sync python -m kconfigs.main config.ini \
              --state ../gh-pages/state.json \
              --output-dir ../gh-pages/out
          uv run --frozen --no-dev --no-sync python -m kconfigs.cleanup config.ini \
              --input-dir ../gh-pages/out
          uv run --frozen --no-dev --no-sync python -m kconfigs.analyzer config.ini \
              --input-dir ../gh-pages/out \
              --output-file ../gh-pages/docs/summary.json
          cp index.html tux-sm.png ../gh-pages/docs/
      - name: Push update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../gh-pages
          git add .
          git commit -m "Automatic update"
          git push origin gh-pages
